config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #

  resources :flights, only: %i[index show]
  root 'flights#index'

  resources :bookings, only: %i[new create show index]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: 'Flight', foreign_key: 'departure_airport_id'
  has_many :arriving_flights, class_name: 'Flight', foreign_key: 'arrival_airport_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  before_save :set_arrival_datetime

  belongs_to :departure_airport, class_name: 'Airport'
  belongs_to :arrival_airport, class_name: 'Airport'

  has_many :bookings
  has_many :passengers, through: :bookings

  private

  def set_arrival_datetime
    # Check if depart_date, depart_time, and duration are present
    return unless depart_date.present? && depart_time.present? && duration.present?

    # Combine depart_date and depart_time to a full DateTime object for departure
    departure_datetime = DateTime.parse("#{depart_date} #{depart_time.strftime('%H:%M:%S')}")

    # Calculate arrival DateTime by adding duration (assumed to be in minutes)
    arrival_datetime = departure_datetime + duration.minutes

    # Set the arrival_date and arrival_time attributes
    self.arrival_date = arrival_datetime.to_date
    self.arrival_time = arrival_datetime.to_time
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  validates :name, presence: true
  validates :email, presence: true,
                    format: { with: URI::MailTo::EMAIL_REGEXP, message: 'must be a valid email address' }
  validate :name_cannot_be_blank

  private

  def name_cannot_be_blank
    errors.add(:name, "can't be blank or contain only whitespace") if name.blank? || name.length < 2
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:selected_flight])
    @booking = @flight.bookings.new
    @passengers = []
    params[:num_passengers].to_i.times { @passengers << @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      @booking.passengers.each do |p|
        puts 'starting do loop'
        PassengerMailer.with(passenger: p, booking: @booking).booking_confirm_email.deliver_now
      end
      redirect_to booking_path(@booking), notice: 'Booking Successfully Created'
    else
      # Since save failed, no need to rebuild passengers; they are already built and contain errors if any.
      # You just need to ensure @flight is available for the view as it was in the `new` action.
      @flight = Flight.find(params[:booking][:flight_id])

      # Render the :new template to show the form again, with error messages.
      # The @booking object includes the attempted data and any validation errors.
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: %i[name email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  include ApplicationHelper
  def index
    @airport_options = Airport.all.map { |a| [a.code, a.id] }
    @flight_dates = Flight.distinct.order(arrival_date: :asc).pluck(:arrival_date).map do |d|
      [format_flight_date(d), d]
    end

    @searched_flights = search_flights
  end

  private

  def search_flights
    return [] unless params[:departure_id].present? && params[:arrival_id].present? && params[:flight_date].present?

    puts 'Searching for Flights'
    Flight.where(departure_airport_id: params[:departure_id],
                 arrival_airport_id: params[:arrival_id],
                 arrival_date: params[:flight_date])
  end

  # def search_params
  #   params.require(:flight).permit(:departure_id, :arrival_id, :num_passengers, :arrival_date)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_flight_date(date)
    date.strftime('%m/%d/%Y')
  end

  def format_flight_time(time)
    time.strftime('%I:%M%P')
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/index.html.erb
<h1>All Bookings</h1>
<ul>
  <% @bookings.each do |booking| %>
    <li>
      <%= link_to booking_path(booking) do %>
        flight <%= booking.flight.id %> from <%= booking.flight.departure_airport.code %> to from <%= booking.flight.arrival_airport.code %> for <%=booking.passengers.count%> passengers
      <% end %>
    </li>
  <% end %>
</ul>
<%= link_to "Home", root_path %>

app/views/bookings/new.html.erb
<% if @booking.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
    <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div data-controller = "booking">
  <%= form_with model: @booking do |booking_form| %>
    <%= booking_form.hidden_field :flight_id, value: @flight.id %>
    <div class= "passengers">
      <% @booking.passengers.each_with_index do |passenger, n| %>
        <div data-booking-target = "passenger" class="passenger-fields">
          <h1>Passenger <%= n + 1 %> Details</h1>
          <%= booking_form.fields_for :passengers, passenger do |passenger_info_form| %>
            <%= passenger_info_form.label :name, "Name" %>
            <%= passenger_info_form.text_field :name %>
            <%= passenger_info_form.label :email, "Email" %>
            <%= passenger_info_form.text_field :email %>
            <% unless n == 0 %>
              <%= passenger_info_form.button "Remove Passenger", data: { action: "click->booking#removePassenger" } %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
    <br>
    <button data-action = "click->booking#addPassenger"> Add passenger </button>
    <%= booking_form.submit "Book Flights" %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<h1>Booking Details</h1>
<h2>for flight <%=@booking.flight.id%></h2>
<h3>From: <%=@booking.flight.departure_airport.name%> at <%=format_flight_time @booking.flight.depart_time%> on <%=format_flight_date @booking.flight.depart_date%></h3>
<h3>To: <%=@booking.flight.arrival_airport.name%> at <%=format_flight_time @booking.flight.arrival_time%> on <%=format_flight_date @booking.flight.arrival_date%></h3>
<% @booking.passengers.each_with_index do |passenger,index|%>
  <div>
    <h1>Passenger <%=index + 1 %></h1>
    <p>Name: <%=passenger.name%></p>
  </div>
<%end%>

app/views/flights/_flight_option.html.erb
<div>
  <%= form.radio_button :selected_flight, flight.id %>
  <%= form.label "selected_flight_#{flight.id}", "Flight ##{flight.id} from #{flight.departure_airport.code} to #{flight.arrival_airport.code}; Departs: #{format_flight_time(flight.depart_time)} on #{format_flight_date(flight.depart_date)}; Arrives: #{format_flight_time(flight.arrival_time)} on #{format_flight_date(flight.arrival_date)}" %>
</div>

app/views/flights/index.html.erb
<h1>Search for Flights</h1>
<%= form_with url: flights_path, method: :get do |form| %>
  <%= form.label :departure_id, "Departing Airport:" %>
  <%= form.select :departure_id, options_for_select(@airport_options, params[:departure_id]), {}, { class: "custom-select" } %>
  <%= form.label :arrival_id, "Arriving Airport:" %>
  <%= form.select :arrival_id, options_for_select(@airport_options, params[:arrival_id]), {}, { class: "custom-select" } %>
  <%= form.label :num_passengers, "Number of Passengers" %>
  <%= form.select :num_passengers, options_for_select([1,2,3,4], params[:num_passengers]), {}, { class: "custom-select" } %>
  <%= form.label :flight_date, "Arrival Date" %>
  <%= form.select :flight_date, options_for_select(@flight_dates, params[:flight_date]), {}, { class: "custom-select" } %>
  <%= form.submit "Search for flights", class: "btn btn-primary" %>
<% end %>
<%if @searched_flights.any? %>
  <%= form_with url: new_booking_path, method: :get do |form|%>
    <% @searched_flights.each do |f| %>
      <div>
        <%= form.radio_button :selected_flight, f.id %>
        <%= form.label "selected_flight_#{f.id}", "Flight ##{f.id} from #{f.departure_airport.code} to #{f.arrival_airport.code}; Departs: #{format_flight_time(f.depart_time)} on #{format_flight_date(f.depart_date)}; Arrives: #{format_flight_time(f.arrival_time)} on #{format_flight_date(f.arrival_date)}" %>
      </div>
    <% end %>
    <%= form.hidden_field :num_passengers, value: params[:num_passengers] %>
    <%= form.submit "Choose Flight", class: "btn btn-primary" %>
  <% end %>
<%end %>

app/views/layouts/_header.html.erb
<header class="header">
  <nav>
    <ul class="nav-list">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Bookings", bookings_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div id="messages">
      <% flash.each do |type, message| %>
        <div class="<%= type %>"><%= message %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>